version: '3.8'


networks:
  Symfony:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    networks:
      - Symfony

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./volumes/db/mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: symfony_sonata_admin_dk
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    networks:
      - Symfony

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8008:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    networks:
      - Symfony

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    volumes:
      -  .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - Symfony

  mailhog:
    container_name: programwithgio-mailhog
    image: mailhog/mailhog
    restart: always
    logging:
      driver: "none"
    ports:
      - "8025:8025"
      - "1025:1025"
    external_links:
      - mailhog
    networks:
      - Symfony

  cron:
    container_name: cron
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/var/www/html
      - ./volumes/cron:/var/log/cron