# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
imports:
    - { resource: 'admin/services.yaml' }
parameters:
    images_directory: '%kernel.project_dir%/public/images/'
    pdf_directory: '%kernel.project_dir%/public/pdf/'
    product_directory: '%kernel.project_dir%/public/files/product/'
    locale: uk
services:
    App\Admin\PostAdmin:
        arguments:
            $imagesDirectory: '%images_directory%'

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $productDirectory: '%product_directory%'


    # Admin
    admin.category:
        class: App\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Category, manager_type: orm, label: Category }

    admin.post:
        class: App\Admin\PostAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Post, manager_type: orm, label: Post }
        public: true

    #FAQ
    admin.faq-category:
        class: App\Admin\FAQ\FAQCategoryAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\FAQ\FAQCategory, manager_type: orm, group: 'FAQ', label: FAQCategory }
        calls:
            - [ addChild, [ '@admin.faq-question', 'category' ] ]

    admin.faq-question:
        class: App\Admin\FAQ\FAQQuestionAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\FAQ\FAQQuestion, manager_type: orm ,group: 'FAQ', label: FAQQuestion }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones