# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    images_directory: '%kernel.project_dir%/public/uploads'
    locale: uk
services:
    App\Admin\PostAdmin:
        arguments:
            $imagesDirectory: '%images_directory%'
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        calls:
            - [setAnnotationReader, ['@annotation_reader']]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    admin.category:
        class: App\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Category, manager_type: orm, label: Категорія }

    admin.post:
        class: App\Admin\PostAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Post, manager_type: orm, label: Пост }
        public: true

    #FAQ
    admin.faq-category:
        class: App\Admin\FAQ\FAQCategoryAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\FAQ\FAQCategory, manager_type: orm, label: FAQ категорії }

    admin.faq-question:
        class: App\Admin\FAQ\FAQQuestionAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\FAQ\FAQQuestion, manager_type: orm, label: FAQ запитння та відповді }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones