runroom_sortable_behavior:
  position_handler: runroom.sortable_behavior.service.gedmo_position
  position_field:
    default: position # Default field name for the position
    # Only needed when not using Gedmo
    entities:
      App\Entity\FAQ\FAQCategory: position
      #      App\Entity\Baz: rang
      # Only needed when not using Gedmo
#      sortable_groups:
#        entities:
#          App\Entity\FAQ\FAQCategory: [group]