sonata_admin:
    title: 'Адмінка'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    options:
        default_group: Контент

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
